"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HopModel = void 0;
const modelValidators_1 = require("@app/api/modelValidators");
const parcel_model_schemas_dolomite_1 = require("@datr.tech/parcel-model-schemas-dolomite");
const mongoose_1 = require("mongoose");
const hopSchema = new mongoose_1.Schema(parcel_model_schemas_dolomite_1.hopModelSchema, parcel_model_schemas_dolomite_1.hopModelSchemaOptions);
hopSchema.post('validate', modelValidators_1.modelValidatorAdminStatusId);
hopSchema.post('validate', modelValidators_1.modelValidatorAdminUserId);
hopSchema.post('validate', modelValidators_1.modelValidatorJourneyId);
hopSchema.post('validate', modelValidators_1.modelValidatorResourceId);
exports.HopModel = (0, mongoose_1.model)('HopModel', hopSchema);
